# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Daniel Lewis Mitchell'
tagline:             'Statistician and Data Scientist'
description:         "This is the personal website of Daniel Lewis Mitchell. I'm a statistician and data scientist in Austin, Texas who is interested in computational methods, Bayesian inference, and spatial statistics."
url:                 http://dlmdata.github.io
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Daniel Lewis Mitchell

# Custom vars
version:             1.0.0
